### ISSUE TITLE
Problem with do_elastix_registration.py

### ISSUE THREAD

**Issue by meruicecream** [hsokooti/RegUn#1]
Hi！I have met a problem when i want to run the  do_elastix_registration.py using Pycharm.
Traceback (most recent call last):
  File "D:/RegUn-master/do_elastix_registration.py", line 154, in <module>
    do_elastix_registration()
  File "D:/RegUn-master/do_elastix_registration.py", line 105, in do_elastix_registration
    reg_elx.write_and_submit_job(setting, job_name=job_name, phase=phase, cn=cn, out=out, script_address=backup_script_address)
  File "D:\RegUn-master\Functions\Python\registration_elx\registration_elx.py", line 262, in write_and_submit_job
    queue_info, job_info = sungrid.qstat()
  File "D:\RegUn-master\Functions\Python\sungrid_utils\_tools.py", line 20, in qstat
    xml = qstat2xml(qstat_path=qstat_path)
  File "D:\RegUn-master\Functions\Python\sungrid_utils\_tools.py", line 37, in qstat2xml
    qstatxml = sp.check_output([qstat_path, xml_option], stderr=sp.STDOUT)
  File "C:\Users\13649\AppData\Local\conda\conda\envs\pytorch\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\13649\AppData\Local\conda\conda\envs\pytorch\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\13649\AppData\Local\conda\conda\envs\pytorch\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\13649\AppData\Local\conda\conda\envs\pytorch\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

What can i do to solve this problem? By the way,in chest_segmentation.py,where can i achieve ptpulmo.exe and PulmoDefaultSettings.psf? Thanks a lot

**Comment by hsokooti** [comment]
Hi, with the default settings of the code, it will run over an [Oracle Grid Engine (previously Sun Grid Engine)](http://gridscheduler.sourceforge.net/) cluster. If that is installed on your cluster, the default command `"qstat"` should work ([qstat DOC](https://docs.oracle.com/cd/E19957-01/820-0699/chp5-30/index.html))

To easily debug the code, maybe it could be better to run it in the `"local"` mode first by changing the [do_elastix_registration.py#13](https://github.com/hsokooti/RegUn/blob/e6144109017c812a2f5989c14a9d5ebf34056aad/do_elastix_registration.py#L13) to:

```python
where_to_run = 'local'
```
Unfortunately, the software "ptpulmo.exe" is not publicly available. You can contact [Prof. Berend Stoel](https://www.lumc.nl/org/radiologie/medewerkers/BCStoel) if you need a license for that. All in all, even a primitive segmentation would suffice for this purpose.

**Comment by meruicecream** [comment]
It is exciting to read your article. It seems that i cannot find codes about regression forest, where can i find them ?
Thanks a lot!

**Comment by hsokooti** [comment]
Thank you for your interest in our article. That part is not in this repository, but the code snippet is:
```python
from sklearn.ensemble import RandomForestRegressor


estimator = RandomForestRegressor(random_state=0,
                                  criterion='mse',
                                  n_estimators=number_of_tree,
                                  max_features=m,
                                  oob_score=False,
                                  max_depth=tree_depth,
                                  min_samples_split=min_samples_split,
                                  n_jobs=7)
estimator.fit(train_feature, train_tre)
feature_importance = estimator.feature_importances_
test_predict_tre = estimator.predict(test_feature)
```
